font_family IosevkaTerm Nerd Font Mono
font_size 14
enable_audio_bell no

background_opacity 0.90
dynamic_background_opacity  no
confirm_os_window_close     0

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# unmap keys
map ctrl+shift+equal discard_event
map ctrl+shift+plus discard_event
map ctrl+shift+kp_add discard_event
map ctrl+shift+minus discard_event
map ctrl+shift+kp_subtract discard_event
map ctrl+shift+backspace discard_event

# Theme

window_padding_width 5
# The basic colors

include gruvbox.conf
