font_family Iosevka
font_size 16
enable_audio_bell no

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0

# unmap keys
map ctrl+shift+equal discard_event
map ctrl+shift+plus discard_event
map ctrl+shift+kp_add discard_event
map ctrl+shift+minus discard_event
map ctrl+shift+kp_subtract discard_event
map ctrl+shift+backspace discard_event

# Theme

window_padding_width 5

cursor                    #524f67
cursor_text_color         #e0def4

url_color                 #c4a7e7

visual_bell_color         #c4a7e7
bell_border_color         #c4a7e7

active_border_color       #31748f
inactive_border_color     #403d52

foreground                #e0def4
background                #191724
selection_foreground      #e0def4
selection_background      #403d52

active_tab_foreground     #e0def4
active_tab_background     #26233a
inactive_tab_foreground   #636a86
inactive_tab_background   #191724

# black  (bg3/bg4)
color0                  #26233a
color8                  #6e6a86

# red
color1                  #eb6f92
color9                  #eb6f92

#: green
color2                  #31748f
color10                 #31748f

# yellow
color3                  #f6c177
color11                 #f6c177

# blue
color4                  #9ccfd8
color12                 #9ccfd8

# purple
color5                  #9ccfd8
color13                 #9ccfd8

# aqua
color6                  #eddcba
color14                 #eddcba

# white (fg4/fg3)
color7                  #e0def4
color15                 #e0def4
